language: c
sudo: false
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libmcrypt-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libt1-dev
compiler:
  - gcc
env:
  - PHP_SRC_VERSION=5.3.29
    NGINX_SRC_VERSION=1.6.3

before_script:
  - ./travis/compile.sh

script:
  - ./travis/test.sh