language: c
sudo: required
addons:
  apt:
    packages:
      - locales
      - language-pack-de
      - re2c
      - libgmp-dev
      - libicu-dev
      - libmcrypt-dev
      - libtidy-dev
      - libenchant-dev
      - libaspell-dev
      - libpspell-dev
      - librecode-dev
      - libsasl2-dev
      - libxpm-dev
      - libt1-dev
      - cpanminus
compiler:
  - gcc
cache:
  - apt
env:
  #- PHP_SRC_VERSION=5.3.29
  #  NGINX_SRC_VERSION=1.7.12
  #- PHP_SRC_VERSION=5.4.45
  #  NGINX_SRC_VERSION=1.7.12
  #- PHP_SRC_VERSION=5.5.38
  #  NGINX_SRC_VERSION=1.7.12
  - PHP_SRC_VERSION=5.6.36
    NGINX_SRC_VERSION=1.10.3
  - PHP_SRC_VERSION=5.6.36
    NGINX_SRC_VERSION=1.8.1
install:
  - sudo cpanm -n Test::Nginx
before_script:
  - ./travis/compile.sh

script:
  - ./travis/test.sh